[package]
name = "docker-compose-types"
description = "Deserialization and Serialization of docker-compose.yml files in a relatively strongly typed fashion."
version = "0.2.0"
edition = "2021"
repository = "https://github.com/stephanbuys/docker-compose-types"
license = "MIT/Apache-2.0"
keywords = ["docker-compose", "compose"]
categories = ["data-structures"]
authors = [
    "Stephan Buys <hello@stephanbuys.com>"
]
readme = "README.md"

[dependencies]
derive_builder = "0.11"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"

[dev-dependencies]
glob = "0.3"
